In [2]:
import numpy as np
list_ = [i for i in range(1,6)]
array_list = np.array(object = list_)
array_list

array([1, 2, 3, 4, 5])

Q1

There is a difference in data types of 'list_' and 'array_list'.


array_list is an numpy array object


list_ is an list object

In [4]:
print(type(array_list))
print(type(list_))

<class 'numpy.ndarray'>
<class 'list'>


Q2

In [5]:
print('Data types of variable list')
for i in list_:
    print(type(i))
print('\n\n')
for i in array_list:
    print(type(i))

Data types of variable list
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>



<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q3

There is a slight difference in them even after changes. The item in variable list are of int type where as the items in array_list became int32 type. This is a slight difference.

In [7]:
array_list = np.array(object = list_, dtype = int)
print('Data types of variable list')
for i in list_:
    print(type(i))
print('\n\n')
for i in array_list:
    print(type(i))

Data types of variable list
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>



<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [8]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4

In [17]:
print('The shape of variable array is: ({},{})'.format(len(num_list),len(num_list[0])))
print('The shape of numpy array is:',num_array.shape)
print('The size of variable array is: {}'.format(len(num_list[0])+len(num_list[1])))
print('The size of numpy array is:',num_array.size)


The shape of variable array is: (2,3)
The shape of numpy array is: (2, 3)
The size of variable array is: 6
The size of numpy array is: 6


Q5

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q5

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])